flags: {}
allow-newer: true
# we use stack inside of nix instead of the other way around
nix:
  enable: true
  pure: false
  packages: [ zlib.dev zlib.out pkgconfig ]
packages:
- .
- ortholang
- ortholang/logging

# it works best if this matches the haskell.compiler.ghcXXX version in default.nix
system-ghc: true
resolver: lts-14.4
extra-deps:
  - posix-escape-0.1
  - path-io-1.6.0
  - progress-meter-1.0.0.1

# TODO are the rtsopts a problem? see if removing fixes any fails
ghc-options:
        # "all": -O2
        # "OrthoLang": -O0
